### ISSUE TITLE
ログアウト時に表示されるフラッシュメッセージの翻訳がない

### ISSUE THREAD

**Issue by fugakkbn** [kaigionrails/cfp-app#2]
CFP App からログアウトした時にページ上部にフラッシュメッセージが表示されますが、そこが以下のようになっていて翻訳が設定されてなさそうです。

<img width="1059" alt="スクリーンショット 2022-06-21 21 15 12" src="https://user-images.githubusercontent.com/58870882/174797525-66ef89f0-ba56-421a-95ca-6d1e694a8ea0.png">

**Comment by unasuke** [comment]
修正しました！

**Comment by fugakkbn** [comment]
はやいっ！
ありがとうございます🙏
